import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { validateUser } from "@/actions";
import { cookies } from "next/headers";
import { useEffect, useState } from "react";
import { User } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await validateUser(cookies().get("jwt")?.value);

  return (
    <html lang="en">
      <body>
        <Link href="/"><h1>Cyber Wargame</h1></Link>
        <>
          {user ? (
            <p>Welcome, {user.username}! <Link href={"/logout"}>Log out?</Link></p>
          ) : (
            <p>You are not currently logged in.</p>
          )}
        </>
        {children}
      </body>
    </html>
  );
}
