// Interface automatically generated by schemas-to-ts

export interface Message {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    message: string;
    date: Date;
    sender: string;
    receiver: string;
  };
}
export interface Message_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  message: string;
  date: Date;
  sender: string;
  receiver: string;
}

export interface Message_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  message: string;
  date: Date;
  sender: string;
  receiver: string;
}

export interface Message_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  message: string;
  date: Date;
  sender: string;
  receiver: string;
}
