// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Message {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    sender?: { data: User };
    receiver?: { data: User };
    message: string;
  };
}
export interface Message_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sender?: User_Plain;
  receiver?: User_Plain;
  message: string;
}

export interface Message_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sender?: number;
  receiver?: number;
  message: string;
}

export interface Message_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sender?: AdminPanelRelationPropertyModification<User_Plain>;
  receiver?: AdminPanelRelationPropertyModification<User_Plain>;
  message: string;
}
