// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Message {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    users_permissions_user?: { data: User };
    content?: string;
    Time?: Date;
  };
}
export interface Message_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  users_permissions_user?: User_Plain;
  content?: string;
  Time?: Date;
}

export interface Message_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  users_permissions_user?: number;
  content?: string;
  Time?: Date;
}

export interface Message_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  users_permissions_user?: AdminPanelRelationPropertyModification<User_Plain>;
  content?: string;
  Time?: Date;
}
