// Interface automatically generated by schemas-to-ts

import { PlaceholderAction } from '../../../../components/actions/interfaces/PlaceholderAction';
import { PlaceholderAction_Plain } from '../../../../components/actions/interfaces/PlaceholderAction';
import { PlaceholderAction_NoRelations } from '../../../../components/actions/interfaces/PlaceholderAction';

export interface Action {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Action: PlaceholderAction[];
  };
}
export interface Action_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Action: PlaceholderAction_Plain[];
}

export interface Action_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Action: PlaceholderAction_NoRelations[];
}

export interface Action_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Action: PlaceholderAction_Plain[];
}
