query(
  $user: String = "test"
  $team: String = "Team 1"
  $teamRole: String = "leader"
) {
  actionLog: resolvedActions(
    pagination: { limit: 100 }
    sort: "date:desc"
    filters: { user: { eq: $user } }
  ) {
    data {
      attributes {
        action {
          name
          description
          teamRole
        }
        date
        endState
      }
    }
  }

  actions(filters: { action: { teamRole: { eq: $teamRole } } }) {
    data {
      id
      attributes {
        action {
          name
          duration
          description
          teamRole
          type
          successRate
          targets {
            target
            myTeam
          }
        }
      }
    }
  }

  modifiers: teams(filters: { name: { eq: $team } }) {
    data {
      attributes {
        leaderModifiers {
          offense
          defense
          buff
        }
      }
    }
  }

  nodes(filters: {}) {
    data {
      id
      attributes {
        name
        defense
        isCoreNode
        visible
      }
    }
  }

  edges(filters: {}) {
    data {
      id
      attributes {
        source {
          data {
            id
          }
        }
        target {
          data {
            id
          }
        }
        defense
      }
    }
  }
}
