// Interface automatically generated by schemas-to-ts

export enum TeamRole {
  Leader = 'leader',
  Intelligence = 'intelligence',
  Military = 'military',
  Media = 'media',
  Diplomat = 'diplomat',}

export interface PlaceholderAction {
  Name?: string;
  Description?: string;
  Duration?: number;
  TeamRole?: TeamRole;
}
export interface PlaceholderAction_Plain {
  Name?: string;
  Description?: string;
  Duration?: number;
  TeamRole?: TeamRole;
}

export interface PlaceholderAction_NoRelations {
  Name?: string;
  Description?: string;
  Duration?: number;
  TeamRole?: TeamRole;
}

